# Generated by Django 4.1.3 on 2023-11-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('roll', models.CharField(max_length=70)),
                ('city', models.IntegerField()),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
