# Generated by Django 4.1.3 on 2023-11-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='city',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='roll',
            field=models.IntegerField(),
        ),
    ]
